{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vote-app.fullname" . }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "" | quote }}
  rules:
    - host: {{ .Values.ingress.host | default "" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vote-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}

