apiVersion: v2
name: vote-app
description: A simple Node.js Express vote app
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: replicated
    repository: oci://registry.replicated.com/library
    version: 1.8.0

