replicaCount: 1

image:
  repository: proxy.replicated.com/proxy/vote/ghcr/grantmiller/vote-app
  pullPolicy: IfNotPresent
  tag: "main"

service:
  type: ClusterIP
  port: 80
  # Set when type is NodePort
  nodePort: null

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: PORT
    value: "3000"

ingress:
  enabled: false
  className: ""
  host: ""
  annotations: {}


# Image pull secrets for private registries, e.g.
# imagePullSecrets:
#   - name: my-registry-secret
imagePullSecrets: []
