replicaCount: 1

image:
  repository: ghcr.io/your-org/vote-app
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: PORT
    value: "3000"

ingress:
  enabled: false
  className: ""
  host: ""
  annotations: {}

